cluster:
  name: ${CLUSTER_NAME}

node:
  master: ${NODE_MASTER}
  data: ${NODE_DATA}

bootstrap.mlockall: ${MLOCKALL}

network.host: 0.0.0.0
http.enabled: ${HTTP_ENABLE}

discovery.zen.ping.multicast.enabled: ${MULTICAST}

index.number_of_replicas: ${INITIAL_REPLICAS}
index.number_of_shards: ${INITIAL_SHARDS}

script.groovy.sandbox.enabled : ${SCRIPT_ENABLE}
script.inline: ${SCRIPT_ENABLE}
