############################## Network And HTTP ###############################

network.bind_host: 0.0.0.0
network.publish_host: _non_loopback:ipv4_

################################## Discovery ##################################

discovery.zen.minimum_master_nodes: 1
discovery.zen.ping.multicast.address: _lo:ipv4_
discovery.zen.fd.ping_interval: 10s
discovery.zen.fd.ping_timeout: 15s
discovery.zen.fd.ping_retries: 1
discovery.type: zen
gateway.local.initial_shards: 1
index.number_of_replicas: 0
index.number_of_shards: 1

# bootstrap.mlockall: true
script.groovy.sandbox.enabled : true
script.inline: true
action.auto_create_index: false
